plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/home/openclaw/openclaw-command-center/projects/jasonead-site-rebuild"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]